name: Build and Pack

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies and execute flet pack
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt  # Replace with your requirements file if needed
        flet pack main.py
        deactivate  # Deactivate the virtual environment

    - name: Publish Artifact for Linux
      uses: actions/upload-artifact@v2
      with:
        name: Bike maintenance tool - Linux
        path: dist/main

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies and execute flet pack
      run: |
        python -m venv venv
        .\venv\Scripts\Activate  # Activate virtual environment on Windows
        pip install -r requirements.txt  # Replace with your requirements file if needed
        flet pack main.py
        deactivate  # Deactivate the virtual environment

    - name: Download and Install NSIS
      run: |
        $nsisPath = "$env:USERPROFILE\nsis"
        New-Item -ItemType Directory -Path $nsisPath -Force
        Invoke-WebRequest -Uri 'https://prdownloads.sourceforge.net/nsis/nsis-3.06.1-setup.exe' -OutFile $nsisPath\nsis-setup.exe
        Start-Process -Wait -FilePath "$nsisPath\nsis-setup.exe" -ArgumentList '/S'

    - name: Compile NSIS Script
      run: |
        & 'C:\Program Files (x86)\NSIS\makensis.exe' installer_files/windows_installer.nsi

    - name: Publish Artifact for Windows
      uses: actions/upload-artifact@v2
      with:
        name: Bike maintenance tool - Windows Installer
        path: .
