name: Build and Pack

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Replace with your requirements file if needed

    - name: Execute flet pack
      run: |
        flet pack your_program.py

    - name: Cleanup
      run: |
        deactivate  # Deactivate the virtual environment
