name: Build and Pack

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies and execute flet pack
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt  # Replace with your requirements file if needed
        flet pack main.py
        deactivate  # Deactivate the virtual environment

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Bike maintenance tool
        path: dist/main
